import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

@NgModule({
  imports: [
  //   CommonModule,
  //   FlexLayoutModule,
  //   MatRadioModule,
  //   MatButtonModule,
  //   MatExpansionModule,
  //   MatToolbarModule,
  //   MatSelectModule,
  //   MatTabsModule,
  //   MatInputModule,
  //   MatProgressSpinnerModule,
  //   MatProgressSpinnerModule,
  //   MatChipsModule,
  //   MatCardModule,
  //   MatSidenavModule,
  //   MatCheckboxModule,
  //   MatListModule,
  //   MatMenuModule,
  //   MatIconModule,
  //   MatTooltipModule,
  //   MatSnackBarModule,
  //   MatSlideToggleModule,
  //   MatDividerModule,
  //   MatProgressSpinnerModule,
  //   MatAutocompleteModule,
  //   MatTableModule,
  //   MatDialogModule,
  //   A11yModule,
  //   CdkStepperModule,
  //   CdkTableModule,
  //   CdkTreeModule,
  //   MatBadgeModule,
  //   MatBottomSheetModule,
  //   MatButtonToggleModule,
  //   MatStepperModule,
  //   MatDatepickerModule,
  //   MatNativeDateModule,
  //   MatGridListModule,
  //   MatNativeDateModule,
  //   MatPaginatorModule,
  //   MatProgressBarModule,
  //   MatRippleModule,
  //   MatSliderModule,
  //   MatSortModule,
  //   MatTreeModule,
  //   PortalModule,
  //   NgxMatSelectSearchModule,

  //   ChartsModule
  // ],
  // declarations: [],
  // exports: [
  //   FlexLayoutModule,
  //   MatRadioModule,
  //   MatButtonModule,
  //   MatExpansionModule,
  //   MatToolbarModule,
  //   MatSelectModule,
  //   MatTabsModule,
  //   MatInputModule,
  //   MatProgressSpinnerModule,
  //   MatChipsModule,
  //   MatCardModule,
  //   MatSidenavModule,
  //   MatCheckboxModule,
  //   MatListModule,
  //   MatMenuModule,
  //   MatIconModule,
  //   MatTooltipModule,
  //   MatSnackBarModule,
  //   MatSlideToggleModule,
  //   MatDividerModule,
  //   MatProgressSpinnerModule,
  //   MatProgressSpinnerModule,
  //   MatAutocompleteModule,
  //   MatTableModule,
  //   MatDialogModule,
  //   A11yModule,
  //   CdkStepperModule,
  //   CdkTableModule,
  //   CdkTreeModule,
  //   MatBadgeModule,
  //   MatBottomSheetModule,
  //   MatButtonToggleModule,
  //   MatStepperModule,
  //   MatDatepickerModule,
  //   MatNativeDateModule,
  //   MatGridListModule,
  //   MatNativeDateModule,
  //   MatPaginatorModule,
  //   MatProgressBarModule,
  //   MatRippleModule,
  //   MatSliderModule,
  //   MatSortModule,
  //   MatTreeModule,
  //   PortalModule,
  //   NgxMatSelectSearchModule,

  //   ChartsModule
  ],

  // schemas: [CUSTOM_ELEMENTS_SCHEMA, NO_ERRORS_SCHEMA]
})
export class MaterialModule {}
